config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get 'pages/about'
  get '/myprojects' => 'project#list'
  post '/free' => 'charge#free'
  post '/pay' => 'charge#pay'

  root 'project#index'

  resources :project do
    resources :task, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_many :tasks
  has_many :subscriptions
  has_many :users, through: :subscriptions
  has_many :reviews

  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 500 }
  validates :price, presence: true, numericality: { only_integer: true }

  has_attached_file :image, :styles => { :medium => "680x300>", :thumb => "170x75>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def shortname
    name.length > 25 ? name[0..25] + "..." : name
  end

  def average_rating
    reviews.blank? ? 0 : reviews.average(:star).round(2)
  end

  def price_in_cents
    price*100
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :project

  validates :title, presence: true, length: { maximum: 50 }
  validates :video, presence: true
  validates :project, presence: true

  def next
    project.tasks.where("tag > ? and header = ?", tag, false).order(:tag).first
  end

  def prev
    project.tasks.where("tag < ? and header = ?", tag, false).order(:tag).last
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
  validates :name, presence: true, length: {maximum: 25}

  has_many :subscriptions
  has_many :projects, through: :subscriptions
  has_many :reviews

  after_create :send_notification

  def send_notification
    MyMailer.new_user(self).deliver
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(provider: access_token.provider, uid: access_token.uid).first
    if user
      return user
    else
      registered_user = User.where(email: access_token.email).first
      if registered_user
        return registered_user
      else
        user = User.create(
          name: data["name"],
          provider: access_token.provider,
          email: data["email"],
          uid: access_token.uid,
          image: data["image"],
          password: Devise.friendly_token[0,20]
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :remember_me, :current_password) }
  end
end

app/controllers/charge_controller.rb
class ChargeController < ApplicationController

  before_action :authenticate_user!

  def free
    project = Project.find(params[:project_id])
    current_user.subscriptions.create(project: project)
    redirect_to project
  end

  def pay
    project = Project.find(params[:project_id])
    customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => project.price_in_cents,
      :description => project.name,
      :currency    => 'usd'
    )

    if charge
      current_user.subscriptions.create(project: project)
      redirect_to project
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to project
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController

  before_action :authenticate_user!, only: [:list]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks.order(:tag)
    @users = @project.users.order('created_at desc').first(10)
    @joined = false
    if !current_user.nil? && !current_user.projects.nil?
      @joined = current_user.projects.include?(@project)
    end
    @review = Review.new
    @reviews = @project.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def list
    if !current_user.nil?
      @projects = current_user.projects
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.create(review_params)
    project = @review.project
    redirect_to project
  end

  def destroy
    @review = Review.find(params[:id])
    project = @review.project
    @review.destroy
    redirect_to project
  end

  private
  def review_params
    params.require(:review).permit(:star, :comment, :project_id, :user_id)
  end

end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :authenticate_user!
  def show
    project = Project.find(params[:project_id])
    @tasks = project.tasks.order(:tag)
    joined = false
    if !current_user.nil? && !current_user.projects.nil?
      joined = current_user.projects.include?(project)
    end

    if joined
      @task = @tasks.find(params[:id])
      @next_task = @task.next
      @prev_task = @task.prev
    else
      flash[:notice] = "Permission denied"
      redirect_to project
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    if user.image
      user.image
    else
      "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=40"
    end
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div(:line_numbers => :table)
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true, :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :strikethrough => true,
      :lax_html_block => true,
      :superscript => true
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options )
    markdown_to_html.render(text).html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code4pro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "shared/header" %>
<%= render partial: "shared/message" %>

<main>
  <div class="container">
    <%= yield %>
  </div>
</main>

<%= render partial: "shared/footer" %>

</body>

<script>
  $(".button-collapse").sideNav();
  $(".dropdown-button").dropdown();
</script>

</html>

app/views/pages/about.html.erb
<h3>About me</h3>
<div class="card z-depth-3">
  <div class="card-content white-text">
    <div class="row">
      <div class="col m6">
        <a class="twitter-timeline" href="https://twitter.com/Code4Startup" data-widget-id="587633580509044736">Tweets by @code4Startup</a>
        <script>
          !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
        </script>
      </div>
      <div class="col m6">
        <div class="card-panel grey lighten-5 z-depth-1">
          <div class="row valign-wrapper">
            <div class="col m3">
              <%= image_tag "avatar.jpg", class: "circle responsive-img" %>
            </div>
            <div class="col m9">
              <span class="black-text">
                I don't know what to say.  Let the world tell you more.. :)
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/project/index.html.erb
<div class="row" data-no-turbolink>
  <br/>

  <% @projects.each do |project| %>
      <%= link_to project do %>
        <div class="col s12 m6 l4">
          <div class="card">
            <div class="card-image waves-effect waves-block waves-light">
              <%= image_tag(project.image, size: "300x300") %>
            </div>
            <div class="card-content" style="height: 6em">
              <span class="cart-title grey-text text-darken-4">
                <%= project.shortname %>
              </span>
            </div>
          </div>
        </div>
      <% end %>
  <% end %>
</div>

app/views/project/list.html.erb
<h1>This is my projects page.</h1>

<div class="row" data-no-turbolink>
  <br/>
  <% if @projects.count > 0 %>
    <% @projects.each do |project| %>
        <%= link_to project do %>
          <div class="col s12 m6 l4">
            <div class="card">
              <div class="card-image waves-effect waves-block waves-light">
                <%= image_tag(project.image, size: "300x300") %>
              </div>
              <div class="card-content" style="height: 6em">
                <span class="cart-title grey-text text-darken-4">
                  <%= project.shortname %>
                </span>
              </div>
            </div>
          </div>
        <% end %>
    <% end %>
  <% else %>
    <div class="center">
      <h5>Currently you are not in any projects</h5>
      <%= link_to "Show all projects", root_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/project/show.html.erb
<div class="row">
  <div class="col m4">
    <div class="card z-depth-2">

      <% if !@joined %>
        <div class="center">
          <h1><%= @project.price == 0? "Free" :  "$#{@project.price}" %> </h1>
        </div>
        <div class="card-action center">

          <% if user_signed_in? %>
            <% if @project.price == 0 %>
              <%= form_tag free_path do %>
                <%= hidden_field_tag 'project_id', @project.id %>
                <button type="submit" class="btn pink darken-2">Take this Project</button>
              <% end %>
            <% else %>
              <%= form_tag pay_path, id:'chargeForm' do %>
                <script src="https://checkout.stripe.com/checkout.js"></script>
                <%= hidden_field_tag 'stripeToken' %>
                <%= hidden_field_tag 'stripeEmail' %>
                <%= hidden_field_tag 'project_id', @project.id %>
                <button id="customButton" type="button" class="btn pink darken-2">Take this Project</button><br>

                <script>
                  var handler = StripeCheckout.configure({
                    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
                    token: function(token, arg) {
                      $('#stripeToken').val(token.id);
                      $('#stripeEmail').val(token.email);
                      $('#chargeForm').submit();
                    }
                  });

                  $('#customButton').on('click', function(e) {
                    handler.open({
                      name: 'Code4Pro',
                      description: '<%= @project.name %>',
                      amount: '<%= @project.price_in_cents %>',
                      email: '<%= current_user.email %>'
                    });
                    e.preventDefault();
                  });
                </script>
              <% end %>
            <% end %>

          <% else %>
            <%= link_to new_user_session_path do %>
              <button type="submit" class="btn pink darken-2">Take this Project</button>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class="card-content center">
          <%= image_tag avatar_url(current_user), class: "circle responsive-img" %></br>
          <h5><%= current_user.name %></h5>
        </div>
        <div class="card-action center">
          <% @users.each do |u| %>
            <span class="valign-wrapper">
              <%= image_tag avatar_url(u), class: "circle responsive-img" %>&nbsp;
              <%= u.name %>
            </span><br>
          <% end %>
        </div>
      <% end %>



    </div>
  </div>

  <div class="col m8">
    <div class="card z-depth-2">
      <div class="card-image">
        <%= image_tag @project.image %>
      </div>

      <div class="row">
        <div class="col s12">
          <ul class="tabs">
            <li class="tab col s3"><a class="active" href="#about">About</a></li>
            <li class="tab col s3"><a href="#videos">Videos</a></li>
            <li class="tab col s3 disabled"><a href="#discussion">Discussion</a></li>
          </ul>
        </div>
        <div id="about" class="col s12">
          <div class="card-content grey-text text-darken-4">
            <h5><%= @project.name %></h5>
            <span id='average_rating'></span>
            <p><%= @reviews.count %> <%= @reviews.count > 1? "Reviews" : "Review" %></p>
            <hr>
            <%= @project.content %>
            <h4>Reviews</h4>
            <div><%= render 'reviews/form' if @joined && !@hasReview %></div>
            <div><%= render 'reviews/index' %></div>
          </div>
        </div>
        <div id="videos" class="col s10 offset-s1">
          <div class="collection" data-no-turbolink>
            <% @tasks.each do |task| %>
              <% if task.header %>
                <div class="collection-item active">
                  <i class="mdi-social-school">&nbsp;<%= task.title %></i>
                </div>
              <% else %>
                <%= link_to [task.project, task], class: "collection-item" do %>
                  <%= task.title %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div id="discussion" class="col s12"></div>
      </div>






    </div>
  </div>
</div>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @project.average_rating %>
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@project, @review]) do |f| %>
  <div id="user_stars"></div>
  <%= f.text_field :comment %>

  <%= f.hidden_field :project_id, value: @project.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#user_stars').raty({
    path: '/assets',
    scoreName: 'review[star]',
    score: 1
  });
</script>

app/views/reviews/_index.html.erb
<% if @reviews.blank? %>
  <span class="center">There are no reviews yet.</span>
<% else %>

  <% @reviews.order("id desc").each do |r| %>
    <hr>
    <div class="row">
      <div class="col m1">
        <%= image_tag avatar_url(r.user), class: "circle responsive-img" %>
      </div>
      <div class="col m10">
        <div>
          <strong><%= r.user.name %></strong>
          <span class="right"><%= distance_of_time_in_words(r.created_at, Time.now) %> ago</span>
        </div>
        <div id='stars_<%= r.id %>'></div>
        <div><%= r.comment %></div>
        <div>
          <%= link_to "Remove", [@project, r], method: :delete, data: {confirm: "Are you sure"} if current_user && current_user.id == r.user.id %>
        </div>
      </div>
    </div>
    <script>
      $('#stars_<%= r.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= r.star %>
      });
    </script>
  <% end %>


<% end %>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer light-blue darken-1">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Code4Pro</h5>
        <p class="grey-text text-lighten-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed aliquam turpis, vitae eleifend turpis. Integer non tempus odio, ut interdum ex. Phasellus malesuada, nisi eu pretium venenatis, nisl lacus iaculis quam, eu suscipit risus enim non sem. Phasellus consectetur tincidunt purus, placerat aliquam quam. Nullam ac quam nunc. Proin posuere dui ut lectus feugiat interdum. Morbi elit odio, ornare ullamcorper eleifend vel, tempus quis turpis.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Social</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Google Plus</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2015 Copyright Code4Pro
      <%= link_to "About Us", pages_about_path, :class => "grey-text text-lighten-4 right" %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li><%= link_to "My Projects", myprojects_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li><%= link_to "My Projects", myprojects_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>
  <nav class='light-blue darken-1 z-depth-2'>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to "Code4Pro", root_path, class: "brand-logo" %>

        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "Projects", root_path %></li>
          <% if !user_signed_in? %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% else %>
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
              <%= image_tag avatar_url(current_user), class: "circle responsive-img" %>&nbsp;
              <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a>
            </li>
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><%= link_to "Projects", root_path %></li>
          <% if !user_signed_in? %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% else %>
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
              <%= image_tag avatar_url(current_user), class: "circle responsive-img" %>&nbsp;
              <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script
<% end %>

app/views/task/show.html.erb
<div class="row" data-no-turbolink>
  <div class="col m4">
    <div class="card z-depth-2">
      <div class="card-content">
        <div class="collection">
          <% @tasks.each do |task| %>
            <% if task.header %>
              <div class="collection-item active">
                <i class="mdi-social-school"> <%= task.title %> </i>
              </div>
            <% else %>
              <%= link_to [task.project, task], class: "collection-item" do %>
                <%= task.title %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col m8">
    <div class="card z-depth-2">
      <div id="wistia_<%= @task.video %>"></div>

      <div class="row">
        <div class="col m6">
          <% if !@prev_task.nil? %>
            <%= link_to "Prev", [@prev_task.project, @prev_task], class: "btn btn-primary" %>
          <% else %>
            &nbsp;
          <% end %>
        </div>
        <div class="col m6">
          <% if !@next_task.nil? %>
            <span class="right">
              <%= link_to "Next", [@next_task.project, @next_task], class: "btn btn-primary" %>
            </span>
          <% end %>
        </div>
      </div>

      <div class="card-action grey-text text-darken-4">
        <button class="btn btn-primary" onclick="setPlaySpeed(0.75)">0.75x</button>
        <button class="btn btn-primary" onclick="setPlaySpeed(1)">1x</button>
        <button class="btn btn-primary" onclick="setPlaySpeed(1.25)">1.25x</button>
        <button class="btn btn-primary" onclick="setPlaySpeed(1.5)">1.5x</button>
        <button class="btn btn-primary" onclick="setPlaySpeed(2)">2x</button>
        <h5><%= @task.title %></h5>
        <hr>
        <%= markdown(@task.note) %>
      </div>
    </div>
  </div>
</div>

<script src="https://fast.wistia.net/static/E-v1.js"></script>
<script>
  wistiaEmbed = Wistia.embed("<%= @task.video %>", {
    videoQuality: "hd-only",
    videoFoam: true
  });

  function setPlaySpeed(speed) {
    wistiaEmbed.playbackRate(speed);
  }
</script>